apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-apache2
  namespace: prueba-desafiok8s
  labels:
    app: website-apache2
spec:
  replicas: 3  # El número de réplicas que necesites
  selector:
    matchLabels:
      app: website-apache2
  strategy:
    type: RollingUpdate  # Estrategia de actualización
    rollingUpdate:
      maxSurge: 1  # Máximo de pods adicionales durante la actualización
      maxUnavailable: 0  # Máximo de pods no disponibles durante la actualización
  template:
    metadata:
      labels:
        app: website-apache2
    spec:
      containers:
      - name: website
        image: fcongedo/mi-web-apache2:5
        ports:
        - containerPort: 80